server:
  port: 8081

spring:
  application:
    name: commercial-service

  datasource:
    url: jdbc:postgresql://localhost:5432/commercial_db
    username: syriamart_admin
    password: supersecretpassword # Bolder quote used due to special characters

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.web: DEBUG
        security.authorization: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown
  endpoint:
    health:
      show-details: always

jwt:
  secret: YourSuperSecretKeyMustBeSharedBetweenServices!!

eureka:
  client:
    service-url:
      # This is the address of the Phonebook we just started!
      defaultZone: http://localhost:8761/eureka/
  instance:
    # This tells Eureka to use the service's IP address rather than the host name
    prefer-ip-address: true